//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismApp {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TourismApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Туризм - Приложение.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить JSON.
        /// </summary>
        internal static string BtnLoadJson {
            get {
                return ResourceManager.GetString("BtnLoadJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить XML.
        /// </summary>
        internal static string BtnLoadXml {
            get {
                return ResourceManager.GetString("BtnLoadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать отели.
        /// </summary>
        internal static string BtnShowHotels {
            get {
                return ResourceManager.GetString("BtnShowHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать туристов.
        /// </summary>
        internal static string BtnShowTourists {
            get {
                return ResourceManager.GetString("BtnShowTourists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать туры.
        /// </summary>
        internal static string BtnShowTours {
            get {
                return ResourceManager.GetString("BtnShowTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отели.
        /// </summary>
        internal static string LabelHotels {
            get {
                return ResourceManager.GetString("LabelHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Туристы.
        /// </summary>
        internal static string LabelTourists {
            get {
                return ResourceManager.GetString("LabelTourists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Туры.
        /// </summary>
        internal static string LabelTours {
            get {
                return ResourceManager.GetString("LabelTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите сущность для загрузки.
        /// </summary>
        internal static string MsgChooseEntity {
            get {
                return ResourceManager.GetString("MsgChooseEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не найден!.
        /// </summary>
        internal static string MsgFileNotFound {
            get {
                return ResourceManager.GetString("MsgFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружено отелей:.
        /// </summary>
        internal static string MsgHotelsLoaded {
            get {
                return ResourceManager.GetString("MsgHotelsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string MsgInfo {
            get {
                return ResourceManager.GetString("MsgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JSON файл не найден!.
        /// </summary>
        internal static string MsgJsonFileNotFound {
            get {
                return ResourceManager.GetString("MsgJsonFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки:.
        /// </summary>
        internal static string MsgLoadError {
            get {
                return ResourceManager.GetString("MsgLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные пусты.
        /// </summary>
        internal static string MsgNoData {
            get {
                return ResourceManager.GetString("MsgNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл для загрузки.
        /// </summary>
        internal static string MsgSelectFile {
            get {
                return ResourceManager.GetString("MsgSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        internal static string MsgSuccess {
            get {
                return ResourceManager.GetString("MsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружено туристов:.
        /// </summary>
        internal static string MsgTouristsLoaded {
            get {
                return ResourceManager.GetString("MsgTouristsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружено туров:.
        /// </summary>
        internal static string MsgToursLoaded {
            get {
                return ResourceManager.GetString("MsgToursLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неподдерживаемый формат файла.
        /// </summary>
        internal static string MsgUnsupportedFormat {
            get {
                return ResourceManager.GetString("MsgUnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XML файл не найден!.
        /// </summary>
        internal static string MsgXmlFileNotFound {
            get {
                return ResourceManager.GetString("MsgXmlFileNotFound", resourceCulture);
            }
        }
    }
}
